POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "test5",
  "email": "test5@gmail.com",
  "password": "123456"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test5@gmail.com",
  "password": "123456"
}

### IMPORT DATA (Chỉ chạy 1 lần)
POST http://localhost:8080/api/import

### LẤY DANH SÁCH CATEGORY (CHỦ ĐỀ)
GET http://localhost:8080/categories

### LẤY DANH SÁCH TỪ VỰNG TRONG CATEGORY ID 1
GET http://localhost:8080/categories/6/flashcards